global:
  pre_a_selected: 
    - 5.0
    - 10.0
    - 25.0
    - 50.0
    - 100.0
  pre_frame_rate:
    - 24.0
    - 12.0
    - 6.0 
    - 1.0
  pre_bitrate:
    - 1000.0
    - 500.0 
    - 100.0
    - 10.0
  ipcamlist:
    - 8:
      - illegal_patking
      - people_counting


dispatcher:
  SLE_trigger_time: 6 # hour 

saver:
  pulsar_url: pulsar://140.114.79.84:6650 
  topic: persistent://video-streaming/raw-video/camera8
  sample_length: 100 # length of captured videos 

SLE:
  algo: FIFO # use which algo to in SLE to decide the sample length
  delta_i: 300







# analytics:

# downsampling_manager:

# downsampling:




