global:
  pre_a_selected: 
    - 5.0
    - 10.0
    - 25.0
    - 50.0
    - 100.0
  pre_frame_rate:
    - 24.0
    - 12.0
    - 6.0 
    - 1.0
  pre_bitrate:
    - 1000.0
    - 500.0 
    - 100.0
    - 10.0
  database_ip: 'localhost'
  database_port: 8087
  database_name: 'merge_storage'
  # camera2SLE: 5000
  # SLE2AP: 7000
  # SLE2camera: 6000

  # agent2DDM: 5001
  # DDM2DP: 7001
  # DP2agent: 6001

  # camera2SLE: 5002
  # SLE2AP: 7002
  # SLE2camera: 6002

  # agent2DDM: 5003
  # DDM2DP: 7003
  # DP2agent: 6003

  # camera2SLE: 5004
  # SLE2AP: 7004
  # SLE2camera: 6004

  # agent2DDM: 5005
  # DDM2DP: 7005
  # DP2agent: 6005

  # camera2SLE: 5006
  # SLE2AP: 7006
  # SLE2camera: 6006

  # agent2DDM: 5007
  # DDM2DP: 7007
  # DP2agent: 6007

  # camera2SLE: 5008
  # SLE2AP: 7008
  # SLE2camera: 6008

  # camera2SLE: 5010
  # SLE2AP: 7010
  # SLE2camera: 6010
  
  # camera2SLE: 5012
  # SLE2AP: 7012
  # SLE2camera: 6012
    
  # camera2SLE: 5014
  # SLE2AP: 7014
  # SLE2camera: 6014


  # camera2SLE: 5016
  # SLE2AP: 7016
  # SLE2camera: 6016
  # camera2SLE: 5018
  # SLE2AP: 7018
  # SLE2camera: 6018

  camera2SLE: 5020
  SLE2AP: 7020
  SLE2camera: 6020

  # camera2SLE: 5016
  # SLE2AP: 7014
  # SLE2camera: 6016

  # camera2SLE: 5018
  # SLE2AP: 7018
  # SLE2camera: 6018

  # camera2SLE: 5020
  # SLE2AP: 7020
  # SLE2camera: 6020

  # camera2SLE: 5021
  # SLE2AP: 7021
  # SLE2camera: 6021

  # camera2SLE: 5023
  # SLE2AP: 7023
  # SLE2camera: 6023

  # camera2SLE: 5025
  # SLE2AP: 7025
  # SLE2camera: 6025

  # camera2SLE: 5027
  # SLE2AP: 7027
  # SLE2camera: 6027
  
  # agent2DDM: 5009
  # DDM2DP: 7009
  # DP2agent: 6009

  # agent2DDM: 5011
  # DDM2DP: 7011
  # DP2agent: 6011


  # agent2DDM: 5013
  # DDM2DP: 7013
  # DP2agent: 6013

  # agent2DDM: 5015
  # DDM2DP: 7015
  # DP2agent: 6015


  # agent2DDM: 5017
  # DDM2DP: 7017
  # DP2agent: 6017


  # agent2DDM: 5019
  # DDM2DP: 7019
  # DP2agent: 6019

  # agent2DDM: 5021
  # DDM2DP: 7021
  # DP2agent: 6021

  # agent2DDM: 5023
  # DDM2DP: 7023
  # DP2agent: 6023

dispatcher:
  SLE_trigger_time: 6 # hour 

saver:
  pulsar_url: pulsar://140.114.79.84:6650 
  topic: persistent://video-streaming/raw-video/camera8
  sample_length: 100 # length of captured videos 


SLE:
  algo: FIFO # use which algo to in SLE to decide the sample length
  delta_i: 300

DDM:
  algo: None

# analytics:

# downsampling_manager:

db_agent:
  DDM_threshold: 5120



